# Generated by Django 2.2.10 on 2020-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('complete', models.IntegerField(choices=[(0, 'Undone'), (1, 'Done')], default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
